#!/bin/bash

# Packages
set -eux

if [[ $(uname) = 'Darwin' ]]; then

  which brew || (
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew update
  )


  which git || brew install git

  which git-lfs || brew install git-lfs

  # tig - text-mode interface for Git - use 'h' to get help
  which tig || brew install tig

  # Recursively search for PATTERN in PATH. Like grep or ack, but faster.
  which ag || brew install the_silver_searcher

  which tmux || brew install tmux

  which jq || brew install jq

  which bat || brew install bat

  [[ $SHELL = "/bin/zsh" ]] || (
    brew install zsh;
    sudo chsh -s /bin/zsh `whoami`
  )

  which direnv || brew install direnv

else

  sudo apt-get update -y

  sudo apt-get install -y software-properties-common

  which git || sudo apt-get install -y git git-lfs
  # todo test that the above works with git-lfs
  which git || sudo apt-get install -y tig

  which ag || (
    sudo apt-get install -y silversearcher-ag;
    sudo dpkg-divert --local --divert /usr/bin/ag --rename --add /usr/bin/silversearcher-ag
  )

  which tmux || sudo apt-get install -y tmux

  which zsh || sudo apt-get install -y zsh

  which jq || sudo apt-get install jq

  which direnv || (echo "please install a recent version of direnv" && exit 12 ) #
fi

# Symlinks
set +ex

for source in $(find ~/.config/henrjk/*/linked -type f); do
  target=~/$(basename "$source")
  echo "ln -sf $source $target"
  ln -sf $source $target
done

# Theme
base16_eighties

echo "Done."
