#!/bin/bash

# Packages
set -eux

if [[ $(uname) = 'Darwin' ]]; then

  which brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  brew update

  which git || {
    brew install git git-lfs
  }
  

  # Recursively search for PATTERN in PATH. Like grep or ack, but faster.
  which ag || brew install the_silver_searcher

  which tmux || brew install tmux

  which jq || brew install jq

  which bat || brew install bat
  
  [[ $SHELL = "/bin/zsh" ]] || (
    brew install zsh;
    sudo chsh -s /bin/zsh `whoami`
  )

else

  sudo apt-get update -y

  sudo apt-get install -y software-properties-common

  which git || sudo apt-get install -y git

  which ag || (
    sudo apt-get install -y silversearcher-ag;
    sudo dpkg-divert --local --divert /usr/bin/ag --rename --add /usr/bin/silversearcher-ag
  )

  which tmux || sudo apt-get install -y tmux

  which zsh || sudo apt-get install -y zsh

  which jq || sudo apt-get install jq
fi

# Symlinks
set +ex

for source in $(find ~/.config/henrjk/*/linked -type f); do
  target=~/$(basename "$source")
  echo "ln -sf $source $target"
  ln -sf $source $target
done

# Theme
base16_eighties

echo "Done."
